### ISSUE TITLE
Common tags for batch/parsed articles don't work

### ISSUE THREAD

**Issue by AdrianSkar** [karan173/Batch-Save-Pocket#3]
Hi! I've noticed that adding single tags works as expected on both Current and Paste links options (individual) but adding them inside the _Add common tags_ field doesn't. Articles are saved but tags are not.

Browser: Chromium: 80.0.3987.149 (Official Build) (64-bit)
Batch save version: 2.0

**Comment by karan173** [comment]
This should work now (Version 3.0)
